---
title: "BPCA"
author: "Philip Nguyen"
date: "11/8/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(rstan)
library(ggrepel)
```

# 1. Load and Clean Data

```{r}
# load
micV <- read.csv("AdiantumData_FL2020.csv", header=T,sep=",",stringsAsFactors = F)
micV <- micV %>%
  select(-Ca_BS,-Zn,-K_BS,-Mg_BS,-Ca_BS, -ExchAcid)

micV$SpeciesFinal <-factor(micV$SpeciesFinal,levels=c("A","A&V","V","V&P","P"))
micV <- micV %>% select(-FlowID,-SporeID,-StomateID,-PatchSize,-RamNum,-RamDens, -MicSlope,-MicAspect,-AdjMicAspect,-final_MicAspect,-MicHs,-MacAspect,-AdjMacAspect,-final_MacAspect,-MacHs,-HsPos,-DepSoil,-TexComp,-Ca.Mg)

micV <- micV %>% 
  filter(SpeciesFinal!="T") %>%
  filter(SpeciesFinal!="0") %>% 
  filter(SpeciesFinal!="A?") %>% 
  filter(SpeciesFinal!="V?")

# # reorganize state as factor
micV$State <- factor(micV$State,levels=c("PA","NY","NH","VT","ME","QC","QC_PNG"))

final_micV <- micV[12:35]

write.csv(final_micV, "unstand_ada.csv")

```


```{r}

## also eliminate Soil depth as variable because it doesn't really mean much in my data collection process. 

# ## eliminate absence plot, sterile hybrids


```

# 2 Stan

```{r}


```


```{r}
set.seed(200)

dim(final_micV)

N <- dim(final_micV)[1]
D <- dim(final_micV)[2]
K <- 3
data <- list(N = N, D = D, K = K, X = final_micV)

fit <- stan(file = "example-bpca.stan", data = data, chains = 2, iter = 500)

# W = projection matrices
W.means <- apply(extract(fit, "W")[[1]], c(2,3), mean)
# Z = latent factors
z.means <- apply(extract(fit, "Z")[[1]], c(2,3), mean)

alpha.means <- apply(extract(fit, "alpha")[[1]], c(2), mean)

W.means.df <- W.means %>% as.data.frame()

W.means.df

Names <- colnames(final_micV)

ggplot() +
    geom_segment(data=W.means.df, 
                 aes(x=0, y=0, xend=V1, yend=V2), 
                 arrow=arrow(length=unit(0.2,"cm")), 
                 alpha=0.25) +
    geom_text_repel(data=W.means.df, 
                    aes(x=V1, y=V2, label=Names), 
                    size=3, 
                    max.overlaps = 50) + 
  theme_bw() + 
  ggtitle("BPCA")

# K = 3

```